using UnityEngine;
using UnityEngine.SceneManagement;

// Most of the functionality of this script is generated by ChatGPT.
// Persistent game manager. Saves and restores player data across scene transitions.
// Attach to GameManager GameObject under GameRoot. Use DontDestroyOnLoad on GameRoot.
public class GameManager : MonoBehaviour
{
    public static GameManager Instance { get; private set; }

    [Header("Gameplay UI Visibility")]
    [Tooltip("UI_Root GameObject containing HUD, PauseButton, LevelUp etc. Hidden in menu scenes.")]
    [SerializeField] private GameObject gameplayUIRoot;

    private static readonly string[] MenuScenes = { "MainMenu", "Credits", "Setting", "HowToPlay", "Gameover" };

    private int _currentHealth;                                                          // Saved current health
    private int _maxHealth;                                                              // Saved maximum health
    private int _currentExperience;                                                      // Saved experience points
    private int _xpPerLevel;                                                             // Saved XP per level
    private float _critRate;                                                             // Saved critical hit rate
    private float _critDamage;                                                           // Saved critical damage bonus
    private float _dodgeRate;                                                            // Saved dodge chance
    private float _moveSpeed;                                                            // Saved movement speed
    private int _attackDamage;                                                           // Saved attack damage
    private int _projectileCount;                                                        // Saved projectile count
    private float _finalDamageMultiplier = 1f;                                           // Saved final damage multiplier
    private int _chainBounceCount;                                                       // Saved ricochet count
    private int _savedWave;                                                              // Saved current wave index
    private int _score;                                                                  // Run score shown on Gameover
    private int _enemiesKilled;                                                          // Total enemies killed this run
    private float _runStartRealtime;                                                     // Real-time timestamp when the run started
    private float _finalRunDurationSeconds;                                              // Frozen duration after death
    private bool _hasRunStarted;                                                         // Whether this run has entered gameplay
    private bool _runEnded;                                                              // Whether the run has already ended

    // True if we have valid saved data from a previous gameplay scene.
    public bool HasSavedData { get; private set; }

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(transform.root.gameObject);
            return;
        }
        Instance = this;

        // Persist entire GameRoot (parent) so GameManager, UI_Root, EventSystem, SceneTransition survive scene loads
        DontDestroyOnLoad(transform.root.gameObject);

        if (gameplayUIRoot == null)
        {
            var uiRoot = transform.root.Find("UI_Root");
            if (uiRoot != null)
                gameplayUIRoot = uiRoot.gameObject;
        }

        if (gameplayUIRoot == null)
            Debug.LogWarning("GameManager: gameplayUIRoot (UI_Root) not found. Assign it in Inspector.");

        SceneManager.sceneLoaded += OnSceneLoaded;
        // Apply visibility for initial scene
        RefreshHudVisibility(SceneManager.GetActiveScene().name);
    }

    private void OnDestroy()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        if (Instance == this)
            Instance = null;
    }

    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        RefreshHudVisibility(scene.name);

        if (!IsMenuScene(scene.name) && !_hasRunStarted)
            StartRun();
    }

    private void RefreshHudVisibility(string sceneName)
    {
        if (gameplayUIRoot == null) return;

        gameplayUIRoot.SetActive(!IsMenuScene(sceneName));
    }

    private bool IsMenuScene(string sceneName)
    {
        for (int i = 0; i < MenuScenes.Length; i++)
        {
            if (MenuScenes[i] == sceneName)
                return true;
        }

        return false;
    }

    private void StartRun()
    {
        _runStartRealtime = Time.realtimeSinceStartup;
        _finalRunDurationSeconds = 0f;
        _hasRunStarted = true;
        _runEnded = false;
    }

    // Save player data from the given components. Call when HP/XP/upgrades change.
    public void SaveFrom(Player_settings ps, PlayerController pc, RangedShooter rs)
    {
        if (ps == null) return;

        _currentHealth = ps.GetCurrentHealth();
        _maxHealth = ps.GetMaxHealth();
        _currentExperience = ps.GetCurrentExperience();
        _xpPerLevel = ps.GetXPPerLevel();
        _critRate = ps.GetCritRate();
        _critDamage = ps.GetCritDamage();
        _dodgeRate = ps.GetDodgeRate();
        _moveSpeed = pc != null ? pc.moveSpeed : 6f;
        _attackDamage = rs != null ? rs.GetAttackDamage() : 10;
        _projectileCount = rs != null ? rs.GetProjectileCount() : 1;
        _finalDamageMultiplier = rs != null ? rs.GetFinalDamageMultiplier() : 1f;
        _chainBounceCount = rs != null ? rs.GetChainBounceCount() : 0;

        HasSavedData = true;
    }

    // Restore saved data into the given components. Call from Player_settings.Start when entering a gameplay scene.
    public void RestoreTo(Player_settings ps, PlayerController pc, RangedShooter rs)
    {
        if (ps == null || !HasSavedData) return;

        ps.RestoreData(_currentHealth, _maxHealth, _currentExperience, _xpPerLevel, _critRate, _critDamage, _dodgeRate);

        if (pc != null)
            pc.moveSpeed = _moveSpeed;

        if (rs != null)
        {
            rs.SetAttackDamage(_attackDamage);
            rs.SetProjectileCount(_projectileCount);
            rs.SetFinalDamageMultiplier(_finalDamageMultiplier);
            rs.SetChainBounceCount(_chainBounceCount);
        }
    }

    // Save current wave index so the next gameplay scene can continue from the next wave.
    public void SaveWaveProgress(int wave)
    {
        _savedWave = Mathf.Max(0, wave);
    }

    // Get saved wave index. Returns 0 if no wave has been saved yet.
    public int GetSavedWaveProgress()
    {
        return _savedWave;
    }

    // Add score for the current run. Used by XP gain so score matches XP earned.
    public void AddScore(int amount)
    {
        if (amount <= 0) return;
        _score += amount;
    }

    // Get current run score for Gameover UI.
    public int GetScore()
    {
        return _score;
    }

    // Register one enemy death for the current run.
    public void AddEnemyKill()
    {
        _enemiesKilled++;
    }

    // Get total enemy kills for the current run.
    public int GetEnemiesKilled()
    {
        return _enemiesKilled;
    }

    // Freeze run timer and invalidate gameplay restore while keeping stats for Gameover.
    public void PrepareForGameOver()
    {
        if (_hasRunStarted && !_runEnded)
        {
            _finalRunDurationSeconds = Mathf.Max(0f, Time.realtimeSinceStartup - _runStartRealtime);
            _runEnded = true;
        }

        HasSavedData = false;
    }

    // Get elapsed time for the current run. Returns frozen time after death.
    public float GetRunDurationSeconds()
    {
        if (!_hasRunStarted) return 0f;
        if (_runEnded) return _finalRunDurationSeconds;
        return Mathf.Max(0f, Time.realtimeSinceStartup - _runStartRealtime);
    }

    // Clear saved data. Call when starting a new game from main menu.
    public void ClearSavedData(bool preserveScore = false)
    {
        HasSavedData = false;
        _savedWave = 0;
        _enemiesKilled = 0;
        _runStartRealtime = 0f;
        _finalRunDurationSeconds = 0f;
        _hasRunStarted = false;
        _runEnded = false;
        if (!preserveScore)
            _score = 0;
    }
}
