using UnityEngine;

// The attack method in this script is an improved version generated by ChatGPT.

[RequireComponent(typeof(Rigidbody2D))]
public class Enemy_Charge : MonoBehaviour, IHealth, IDamageable
{
    // Enemy states
    private enum ChargeState
    {
        Idle,           // Not detecting player
        Charging,       // Detected player, charging up (staying still)
        Dashing         // Charging complete, dashing towards player
    }

    [SerializeField] private int maxHealth = 30;                                          // Maximum health of the enemy
    [SerializeField] private int attackDamage = 1;                                       // Damage dealt to player on collision
    [SerializeField] private float dashSpeed = 20f;                                      // Speed when dashing towards player
    [SerializeField] private float detectionRange = 30f;                                 // Range to detect player
    [SerializeField] private float chargeTime = 1f;                                      // Time to charge before dashing
    [SerializeField] private float dashDuration = 2f;                                    // Duration of the dash
    [SerializeField] private float damageCooldown = 2f;                                  // Cooldown between damage to player
    [SerializeField] private int experience = 3;                                         // Experience points given to player when killed
    [SerializeField] private GameObject damagePopUpPrefab;                               // Prefab for damage pop-up text (optional)
    [SerializeField] private Animator enemyAnimator;                                      // Animator used to play death animation
    [SerializeField] private AnimationClip idleAnimationClip;
    [SerializeField] private AnimationClip chargingAnimationClip;
    [SerializeField] private AnimationClip dashingAnimationClip;
    [SerializeField] private AnimationClip deathAnimationClip;                            // Death animation clip (choose in Inspector)
    [SerializeField] private AudioClip gotHitClip;                                        // SFX when enemy takes damage
    [Range(0f, 1f)] [SerializeField] private float gotHitVolume = 1f;

    private int currentHealth;                                                           // Current health of the enemy
    private Transform playerTransform;                                                   // Transform of the player (the player's position)
    private Rigidbody2D rb;                                                              // Rigidbody2D component of the enemy
    private float lastDamageTime;                                                        // Time when the enemy last damaged the player
    private ChargeState currentState = ChargeState.Idle;                                 // Current state of the enemy
    private float chargeStartTime;                                                       // Time when charging started
    private float dashStartTime;                                                         // Time when dashing started
    private Vector2 dashDirection;                                                       // Direction to dash towards player
    private bool isDead;                                                                 // Prevent repeated death logic
    private AudioSource _sfxSource;
    private string _currentAnimationState;

    // Start method to initialize the enemy
    void Start()
    {
        currentHealth = maxHealth;
        rb = GetComponent<Rigidbody2D>();
        EnsureSFXSource();
        if (enemyAnimator == null) enemyAnimator = GetComponent<Animator>();
        if (enemyAnimator == null) enemyAnimator = GetComponentInChildren<Animator>();
        UpdateAnimationForState(currentState);

        // Get player transform from singleton
        if (Player_settings.Instance != null)
        {
            playerTransform = Player_settings.Instance.PlayerTransform;
        }
    }

    // FixedUpdate method to handle enemy behavior based on state
    void FixedUpdate()
    {
        if (playerTransform == null) return;

        float distanceToPlayer = Vector2.Distance(transform.position, playerTransform.position);

        // State machine logic
        switch (currentState)
        {
            case ChargeState.Idle:
                // Check if player is within detection range
                if (distanceToPlayer <= detectionRange)
                {
                    // Start charging
                    SetState(ChargeState.Charging);
                    chargeStartTime = Time.time;
                    dashDirection = ((Vector2)playerTransform.position - rb.position).normalized;
                }
                break;

            case ChargeState.Charging:
                // Update dash direction in case player moves during charge
                dashDirection = ((Vector2)playerTransform.position - rb.position).normalized;
                
                // Check if charge time is complete
                if (Time.time >= chargeStartTime + chargeTime)
                {
                    SetState(ChargeState.Dashing);
                    dashStartTime = Time.time;
                }
                // Stay still during charging
                break;

            case ChargeState.Dashing:
                // Check if dash duration has expired
                if (Time.time >= dashStartTime + dashDuration)
                {
                    SetState(ChargeState.Idle);
                    break;
                }

                // Move quickly towards player with obstacle avoidance
                Vector2 currentPos = rb.position;
                Vector2 nextPos = currentPos + dashDirection * dashSpeed * Time.fixedDeltaTime;
                rb.MovePosition(nextPos);

                // If player moved out of range or too far, reset to idle
                if (distanceToPlayer > detectionRange * 1.5f)
                {
                    SetState(ChargeState.Idle);
                }
                break;
        }
    }

    // OnCollisionEnter2D method to damage player when colliding
    void OnCollisionEnter2D(Collision2D collision)
    {
        // Damage player when colliding
        if (collision.gameObject.CompareTag("Player"))
        {
            if (Time.time >= lastDamageTime + damageCooldown)
            {
                Player_settings playerSettings = collision.gameObject.GetComponent<Player_settings>();
                if (playerSettings != null)
                {
                    playerSettings.TakeDamage(attackDamage);
                    lastDamageTime = Time.time;
                    
                    // Reset to idle state after hitting player
                    SetState(ChargeState.Idle);
                }
            }
        }
    }

    private void SetState(ChargeState newState)
    {
        if (currentState == newState) return;
        currentState = newState;
        UpdateAnimationForState(newState);
    }

    private void UpdateAnimationForState(ChargeState state)
    {
        if (enemyAnimator == null) return;

        AnimationClip targetClip = state switch
        {
            ChargeState.Idle => idleAnimationClip,
            ChargeState.Charging => chargingAnimationClip,
            ChargeState.Dashing => dashingAnimationClip,
            _ => null
        };

        if (targetClip == null || _currentAnimationState == targetClip.name) return;

        int stateHash = Animator.StringToHash(targetClip.name);
        if (!enemyAnimator.HasState(0, stateHash)) return;

        enemyAnimator.Play(stateHash, 0, 0f);
        _currentAnimationState = targetClip.name;
    }

    // Take damage from projectiles
    public void TakeDamage(int damage, bool isCrit = false)
    {
        if (isDead) return;

        currentHealth -= damage;

        if (gotHitClip != null && _sfxSource != null)
            _sfxSource.PlayOneShot(gotHitClip, gotHitVolume);

        if (damagePopUpPrefab != null)
        {
            GameObject popup = Instantiate(damagePopUpPrefab, transform.position, Quaternion.identity);
            DamagePopUp popupScript = popup.GetComponent<DamagePopUp>();
            if (popupScript != null)
            {
                popupScript.Init(damage, transform.position, isCrit);
            }
        }

        if (currentHealth <= 0)
        {
            Die();
        }
    }

    // Die method to destroy the enemy and give experience to player
    private void Die()
    {
        if (isDead) return;
        isDead = true;

        if (Player_settings.Instance != null)
        {
            if (GameManager.Instance != null)
                GameManager.Instance.AddEnemyKill();
            Player_settings.Instance.AddExperience(experience);
        }

        if (rb != null) rb.simulated = false;
        Collider2D[] colliders = GetComponentsInChildren<Collider2D>(true);
        foreach (Collider2D col in colliders) col.enabled = false;

        float destroyDelay = 0f;
        if (enemyAnimator != null && deathAnimationClip != null)
        {
            enemyAnimator.Play(deathAnimationClip.name, 0, 0f);
            destroyDelay = deathAnimationClip.length;
        }

        Destroy(gameObject, Mathf.Max(0f, destroyDelay));
    }

    // Get the current health of the enemy
    public int GetCurrentHealth()
    {
        return currentHealth;
    }

    public void ApplyWaveScaling(float healthMultiplier, int damageBonus, int experienceBonus)
    {
        maxHealth = Mathf.Max(1, Mathf.RoundToInt(maxHealth * Mathf.Max(0.1f, healthMultiplier)));
        attackDamage = Mathf.Max(1, attackDamage + damageBonus);
        experience = Mathf.Max(0, experience + experienceBonus);
    }

    // Get the maximum health of the enemy
    public int GetMaxHealth()
    {
        return maxHealth;
    }

    private void EnsureSFXSource()
    {
        if (_sfxSource != null) return;
        _sfxSource = GetComponent<AudioSource>();
        if (_sfxSource == null) _sfxSource = gameObject.AddComponent<AudioSource>();
        _sfxSource.spatialBlend = 0f;
        _sfxSource.playOnAwake = false;
    }
}
